#encoding: utf-8

# Static.create(title: 'Общая информация', body: '', short_url: 'about', template: 'show')
# Static.create(title: 'Документы', body: '', short_url: 'docs', template: 'show')
# Static.create(title: 'Дома', body: '', short_url: 'houses', template: 'houses')
# Static.create(title: 'Заявка', body: '', short_url: 'requests', template: 'request')
# Static.create(title: 'Вакансии', body: '', short_url: 'vacancies', template: 'show')
# Static.create(title: 'Адрес', body: '', short_url: 'address', template: 'address')

# Notice.create(title: "Завершается промывка и опрессовка тепловых систем", body: "Завершается промывка и опрессовка тепловых систем обслуживаемого жилого фонда. 80% зданий впервые за свою историю прошли полный цикл подготовки к отопительному сезону,что обусловило большие сроки проведения указанных работ, в ходе которых были заменены все аварийные задвижки, установлена необходимая запорная и спускная аппаратура.")
# Notice.create(title: "Программа капитального ремонта лежака ГВС", body: "В связи с аварией на системе ГВС МКД Димитрова 20 на рассмотрение собственникам предложена программа капитального ремонта лежака ГВС. Сроки проведения работ зависят от собственников жилья.")

# User.create(:email => "anton@black-sheep.ru", :password => "enlightenment", :role => 0)
# User.create(:email => "nashdom.44@yandex.ru", :password => "myasnizkaja112uk", :role => 0)

House.create(address: "г. Кострома, ул. Симановского, д. 6.", info: "299.70м2")
House.create(address: "г. Кострома, ул. Шагова, д. 6 Б", info: "152.90м2")
House.create(address: "г. Кострома, ул. Шагова, д. 6 А", info: "630.90м2")
House.create(address: "г. Кострома, ул. Шагова, д. 25/8", info: "4382.20м2")
House.create(address: "г. Кострома, пр-кт. Текстильщиков, д. 6", info: "2078.80м2")
House.create(address: "г. Кострома, ул. Советская, д. 7", info: "1880.50м2")
House.create(address: "г. Кострома, ул. Советская, д. 9", info: "329.80м2")
House.create(address: "г. Кострома, ул. Советская, д. 11", info: "350.50м2")
House.create(address: "г. Кострома, ул. Советская, д. 13А", info: "1292.60м2")
House.create(address: "г. Кострома, ул. Симановского, д. 44/35", info: "279.20м2")
House.create(address: "г. Кострома, ул. Симановского, д. 15", info: "307.30м2")
House.create(address: "г. Кострома, ул. Свердлова, д. 46", info: "688.80м2")
House.create(address: "г. Кострома, ул. Островского, д. 42/12", info: "382.30м2")
House.create(address: "г. Кострома, ул. Островского, д. 2", info: "4139.00м2")
House.create(address: "г. Кострома, ул. Овражная, д. 20/23", info: "3830.40м2")
House.create(address: "г. Кострома, ул. Ново-Полянская, д. 7", info: "7168.90м2")
House.create(address: "г. Кострома, ул. Никитская, д. 10", info: "663.10м2")
House.create(address: "г. Кострома, пр-кт. Мира, д. 19", info: "252.70м2")
House.create(address: "г. Кострома, пр-кт. Мира, д. 130", info: "646.00м2")
House.create(address: "г. Кострома, ул. Ленина, д. 1А", info: "2003.70м2")
House.create(address: "г. Кострома, ш. Кинешемское, д. 15", info: "5001.30м2")
House.create(address: "г. Кострома, ул. Крестьянская, д. 10 В", info: "444.00м2")
House.create(address: "г. Кострома, ул. Крестьянская, д. 10 Б", info: "1195.40м2")
House.create(address: "г. Кострома, ул. Крестьянская, д. 10 А", info: "355.30м2")
House.create(address: "г. Кострома, ул. Ивановская, д. 6", info: "391.70м2")
House.create(address: "г. Кострома, ул. Дзержинского, д. 23", info: "1809.90м2")
House.create(address: "г. Кострома, ул. Войкова, д. 41 А", info: "2476.20м2")
House.create(address: "г. Кострома, ул. Горная, д. 11", info: "224.40м2")
House.create(address: "г. Кострома, ул. Симановского, д. 4", info: "347.50м2")
House.create(address: "г. Кострома, мкр. Давыдовский-3, д. 28, к. б", info: "4296.60м2")
House.create(address: "г. Кострома, ул. Шагова, д. 4", info: "1296.60м2")
House.create(address: "г. Кострома, ул. Свердлова, д. 48", info: "671.30м2")
House.create(address: "г. Кострома, ул. Советская, д. 13", info: "1260.30м2")
House.create(address: "г. Кострома, ул. Маршала Новикова, д. 57А", info: "503.80м2")
House.create(address: "г. Кострома, ул. Димитрова, д. 20", info: "3858.30м2")
House.create(address: "г. Кострома, ул. Димитрова 14", info: "1668.40м2")
House.create(address: "г. Кострома, ул. Энгельса, д. 6", info: "402.30м2")
House.create(address: "г. Кострома, ул. Строительный проезд, д. 3", info: "860.60м2")
House.create(address: "г. Кострома, ул. Строительный проезд, д. 4", info: "654.50м2")
House.create(address: "г. Кострома, ул. Строительный проезд, д. 5", info: "645.60м2")
House.create(address: "г. Кострома, ул. Машиностроителей, д. 18", info: "554.90м2")
